Repository yuki-shimoda-crypto/42_ft_transcendence, pull requests merged in 2024-07, with the labels that each got.

#88 [docs]: #87 create-readme
  README.md
  README_ja.md
Labels: documentation

#98 [chore]: #96 自分自身との対戦をできないようにする
  tools/docker/web_prod/docker-entrypoint.sh
Labels: bug

#94 86 feat tournament
  .vscode/launch.json
  PongChat/accounts/migrations/0008_alter_customuser_groups_alter_customuser_is_active_and_more.py
  PongChat/pingpong/admin.py
  PongChat/pingpong/consumers.py
  PongChat/pingpong/migrations/0006_guestuser_tournament_tournamentresults.py
  PongChat/pingpong/migrations/0007_rename_tournamentresults_tournamentmatch.py
  PongChat/pingpong/models.py
  PongChat/pingpong/routing.py
  PongChat/pingpong/static/pingpong/js/tournament/ball.js
  PongChat/pingpong/static/pingpong/js/tournament/game_control.js
  PongChat/pingpong/static/pingpong/js/tournament/key_handle.js
  PongChat/pingpong/static/pingpong/js/tournament/main.js
  PongChat/pingpong/static/pingpong/js/tournament/network.js
  PongChat/pingpong/static/pingpong/js/tournament/paddle.js
  PongChat/pingpong/static/pingpong/js/tournament/score.js
  PongChat/pingpong/static/pingpong/js/tournament/ui.js
  PongChat/pingpong/templates/pingpong/tournament_bracket.html
  PongChat/pingpong/templates/pingpong/tournament_finish.html
  PongChat/pingpong/templates/pingpong/tournament_play.html
  PongChat/pingpong/templates/pingpong/tournament_registration.html
  PongChat/pingpong/urls.py
  PongChat/pingpong/views.py
  docs/tournament-specification.md
  sample_code/__init__.py
  sample_code/inc_dec.py
  sample_code/test.css
  sample_code/test.html
  sample_code/test.js
  sample_code/test.py
  tests/test_inc_dec.py
Labels: enhancement, Game

#103 [feat]: #100 enable-multilantuage
  Dockerfile
  tools/docker/web_prod/docker-entrypoint.sh
Labels: bug, enhancement, chore

#114 [refactor]: #113 modify-chat-style
  PongChat/chat/templates/chat/chat.html
Labels: refactor

#119 [feat]: #118 add-links-to-the-icons-on-the-top-page-service-content
  PongChat/accounts/forms.py
  PongChat/accounts/templates/accounts/top.html
  PongChat/locale/en/LC_MESSAGES/django.po
  PongChat/locale/fr/LC_MESSAGES/django.po
Labels: bug, enhancement

#116 [feat]: #115 health check
  compose.yml
Labels: bug

#121 [type]: #104 feat: ゲームマニュアルの作成
  PongChat/locale/en/LC_MESSAGES/django.po
  PongChat/locale/fr/LC_MESSAGES/django.po
  PongChat/pingpong/templates/pingpong/home.html
  PongChat/pingpong/templates/pingpong/how_to_play.html
  PongChat/pingpong/urls.py
  PongChat/pingpong/views.py
Labels: enhancement

#120 117 refactor remove consolelog during game play
  PongChat/pingpong/static/pingpong/js/multiplay_remote/main.js
  PongChat/pingpong/static/pingpong/js/multiplay_remote/score.js
  PongChat/pingpong/templates/pingpong/tournament_play.html
  compose.yml
Labels: refactor
